SRC_DIR := $(ROOT_DIR)/src
TARGET  := $(ROOT_DIR)/$(OUTPUT)

SRCS := $(sort $(shell find $(SRC_DIR) -name '*.c'))
OBJS := $(patsubst $(SRC_DIR)/%.c,$(BUILD)/obj/%.o,$(SRCS))
DEPS := $(OBJS:.o=.d)
JSON := $(OBJS:.o=.json)

ALL_CFLAGS := $(CFLAGS) -std=c99 -I$(SRC_DIR) -MMD -MP

KEYWORDS := include/syntax/lexer/keywords

all:  $(KEYWORDS).h $(TARGET)

$(KEYWORDS).h: $(KEYWORDS).gperf
	@printf "$(COLOR_MAGENTA)[gperf] %s$(COLOR_RESET)\n" $(notdir $@)
	@gperf -N get_keyword_kind -t $< > $@

$(TARGET): $(OBJS)
	@printf '$(COLOR_GREEN)[+] Linking %s ($(MODE))$(COLOR_RESET)\n' $(notdir $@)
	@$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

$(BUILD)/obj/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	@printf '$(COLOR_YELLOW)[CC] %s$(COLOR_RESET)\n' $(patsubst $(SRC_DIR)/%,%,$<)
	@$(CC) $(ALL_CFLAGS) -MJ $(@:.o=.json) -c $< -o $@

compdb: $(OBJS)
	@{ echo '['; cat $(JSON) | sed '$$ s/,$$//'; echo ']'; } > $(ROOT_DIR)/compile_commands.json
	@printf '$(COLOR_MAGENTA)[=] compile_commands.json ($(words $(SRCS)) files)$(COLOR_RESET)\n'

-include $(DEPS)

.PHONY: all compdb
